baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'IITBHU_CYBERSEC'
[taxonomies]
  category = "categories"
  tag = "tags"
[outputs]
  home = ["HTML", "JSON"]
 relativeURLs = true
canonifyURLs = true
